version: '3.7'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes: 
      - zoodata_value:/var/lib/zookeeper/data
      - zoolog_value:/var/lib/zookeeper/log
#      - ./zoo/data:/var/lib/zookeeper/data
#      - ./zoo/log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092/tcp"
      - "19092:19092"
      - "9092:9092"
    environment:
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://host.docker.internal:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes: 
      - kafka_value:/var/lib/kafka/data

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9900:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"

  kafkaui:
    image: provectuslabs/kafka-ui
    environment:
    - KAFKA_CLUSTERS_0_NAME=local
    - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
    - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    ports:
      - "14080:8080"

  db:
    image: postgres:alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "15432:5432"

  # web:
  #     build: .
  #     restart: always
  #     env_file:
  #       - ./.env
  #     depends_on:
  #       - db
  #       - kafka
  #       - zookeeper
  #     ports:
  #       - "8000:8000"

volumes:
  zoodata_value:
  zoolog_value:
  db_value:
  kafka_value:
